inherit: true
filter:
    excluded_paths:
        - 'build/*'
        - 'tests/*'
tools:
    php_cpd: true
    php_pdepend: true
    php_mess_detector: true
    php_sim: true
    php_changetracking: true
    sensiolabs_security_checker: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    
