language: php
php:
  - 5.2
  - 5.3
  - 5.4
before_script:
  - pyrus install pear/PHP_CodeSniffer
  - pyrus install pear.phpmd.org/PHP_PMD
  - pyrus install pear.pdepend.org/PHP_Depend
  - pyrus install pear.phpdoc.org/phpDocumentor
  - phpenv rehash
script : ant
