---
language: php
os:
- linux
php:
- 5.6
- 7.0

before_install:
- pip install --user codecov

before_script:
- make tools setup

services:
  - mongodb

matrix:
  allow_failures:
  - php: 5.6

script:
- make build doc

after_success:
- codecov
