---
language: php
php:
- 5.3
- 5.4
- 5.5
before_script:
- sudo apt-get install -qq unzip
- ./build/getTools.sh
- phpenv rehash
- composer self-update
- composer install
- composer update

services:
  - mongodb

matrix:
  allow_failures:
  - php: 5.5
script:
- ant travis -Dphpunit.testdox=true -Dpackage.version=$TRAVIS_BUILD_NUMBER
