---
language: php
os:
- linux
php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0
  
before_install:
- pip install --user codecov
- sudo apt-get update -qq
- sudo apt-get install -qq unzip  

before_script:
- echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- composer self-update
- composer install
- wget -nc -O ./phpDocumentor.phar http://www.phpdoc.org/phpDocumentor.phar
- chmod 755 ./phpDocumentor.phar
- wget -nc -O ./phpunit.phar --no-check-certificate https://phar.phpunit.de/phpunit.phar
- chmod 755 ./phpunit.phar
- wget -nc -O ./phpcs.phar --no-check-certificate https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
- chmod 755 ./phpcs.phar
- wget -nc -O ./phpcbf.phar --no-check-certificate https://squizlabs.github.io/PHP_CodeSniffer/phpcbf.phar
- chmod 755 ./phpcbf.phar
- phpenv rehash

services:
  - mongodb

matrix:
  allow_failures:
  - php: 7.0

script:
- rm -rf ./build
- php ./phpunit.phar --testdox -c ./phpunit.xml.dist

after_success:
- codecov
